baseurl = "http://c0dej0ckey.github.io/Site"
languageCode = "en-us"
title = "c0dej0ckey.github.io"
theme = "hyde"
copyright = "Nate Finch"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = "true"


[Author]
	name = "Nate Finch"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "code by Nate Finch"
	twitter = "https://twitter.com/natethefinch"
	github = "https://github.com/natefinch"
	gplus = "https://plus.google.com/+NateFinch"
	disqus = "npfio"

